#!/bin/sh -e

# Enable services
if [ X != "X$(pidof systemd)" ]; then
  echo "Disable {{app}} service"
  systemctl disable {{app}}.service
  systemctl daemon-reload
else
  echo "systemd not available. start services manually"
fi

exit 0
