name: {{name}} build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:21.3.8.2

    steps:
    - uses: actions/checkout@v2

    - name: Create escript
      run: make release

    - name: Upload {{name}}
      uses: actions/upload-artifact@v1
      with:
        name: {{name}}
        path: _build/default/bin/{{name}}

    - name: Create version.txt
      run: _build/default/bin/{{name}} version > version.txt

    - name: Upload {{name}} version artifact
      uses: actions/upload-artifact@v1
      with:
        name: version
        path: version.txt

  release:
    needs: build

    runs-on: ubuntu-latest

    if: endsWith(github.ref, 'refs/heads/master')

    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download {{name}}
      uses: actions/download-artifact@v1
      with:
        name: {{name}}

    - name: Download version.txt
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Push Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

      run: |
        go install github.com/tcnksm/ghr@v0.14.0
        VERSION=$(cat version/version.txt | sed 's/Version: //')
        REPO={{name}}
        OWNER=xaptum-eng
        $HOME/go/bin/ghr \
            -t ${GITHUB_TOKEN} \
            -u ${OWNER} \
            -r ${REPO} \
            -c ${GITHUB_SHA} \
            -delete \
            ${VERSION} {{name}}/{{name}}
