name: Package rebar3 templates

on: [push]

jobs:

  release:

    runs-on: ubuntu-latest

#    if: endsWith(github.ref, 'refs/heads/master')

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout
      uses: actions/checkout@v1

    - name: Create tar file
      run: |
        tar -cvf rebar3-templates.tar *.template common library rustler service
        ls -l

    - name: gzip tar file
      run: |   
        gzip rebar3-templates.tar

    - name: Push Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

      run: |
        go get -u github.com/tcnksm/ghr
        VERSION=$(./ebump current)
        REPO=rebar3-templates
        OWNER=drvspw
        $HOME/go/bin/ghr \
            -t ${GITHUB_TOKEN} \
            -u ${OWNER} \
            -r ${REPO} \
            -c ${GITHUB_SHA} \
            -delete \
            ${VERSION} rebar3-templates.tar.gz
